### PR TITLE
Convert type comments to annotations

### PR DESCRIPTION
**Pull request by jugmac00**
This is another step for #32.

Some notes:
- variable annotations are only possible for Python 3.6 and upwards
- class names as a result of a function have to be quoted
cf https://www.python.org/dev/peps/pep-0563/#enabling-the-future-behavior-in-python-3-7

This can be merged. A next step would be to re-activate some stricter mypy configuration options.

P.S.: For the transformation I used the excellent tool https://github.com/ilevkivskyi/com2ann

### CODE REVIEW

**Comment by jtesta** [comment]
Thanks for this PR!

I noticed, though, that pylint reports the following warnings:
```
ssh-audit.py:97:73: E1136: Value 'Sequence' is unsubscriptable (unsubscriptable-object)
ssh-audit.py:1613:27: E1136: Value 'Sequence' is unsubscriptable (unsubscriptable-object)
ssh-audit.py:1896:74: E1136: Value 'Sequence' is unsubscriptable (unsubscriptable-object)
ssh-audit.py:1920:33: E1136: Value 'Sequence' is unsubscriptable (unsubscriptable-object)
ssh-audit.py:2916:29: E1136: Value 'Sequence' is unsubscriptable (unsubscriptable-object)
ssh-audit.py:2916:47: E1136: Value 'Sequence' is unsubscriptable (unsubscriptable-object)
```

I'm not understanding why it doesn't like the Sequence[] decorator, though.  Any ideas?

**Comment by jugmac00** [comment]
Hi @jtesta 

Neither on my dev machine nor on Travis ( https://travis-ci.org/github/jtesta/ssh-audit/jobs/702072635 ) I can reproduce or see the errors/warnings you experience.

Can you tell exactly what you did? ie the command, and the branch?
Maybe recreate your tox envs by appending the `- r` option.

**Comment by jugmac00** [comment]
```
ssh-audit on  convert-comments-to-annotations [$?] via 🐍 v2.7.17 
❯ tox -e py38-pylint -r
py38-pylint create: /home/jugmac00/Projects/ssh-audit/.tox/py38-pylint
py38-pylint installdeps: mccabe, pylint
py38-pylint installed: astroid==2.4.2,isort==4.3.21,lazy-object-proxy==1.4.3,mccabe==0.6.1,pylint==2.5.3,six==1.15.0,toml==0.10.1,wrapt==1.12.1
py38-pylint run-test-pre: PYTHONHASHSEED='2474958152'
py38-pylint run-test: commands[0] | -pylint --rcfile tox.ini --load-plugins=pylint.extensions.bad_builtin --load-plugins=pylint.extensions.check_elif --load-plugins=pylint.extensions.mccabe /home/jugmac00/Projects/ssh-audit/ssh-audit.py

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

___________________________________________________________ summary ___________________________________________________________
  py38-pylint: commands succeeded
  congratulations :)
```

**Comment by jugmac00** [comment]
pylint has 25 open issues with problems with `unsubscriptable` https://github.com/PyCQA/pylint/issues?q=is%3Aissue+is%3Aopen+unsubscriptable

Personally, I do not use pylint, and none of the open source projects I contribute to, uses it. They all go for flake8, though both tools do not have a 100% overlap.

While we are at it :-D, I also never saw anybody using vulture.

I think using both flake8 and mypy is good enough. There are some more very good linters/formatters out there, like bugbear (prevent bugs), bandit (prevent security problems), isort (sort imports automatically)....

And there is this great tool out there ( https://pre-commit.com/ ) which manages all those linters and formatters and runs them just before you commit, so there are never ever any broken builds (formatting issues) at ci.

P.S.: And pre-commit can prevent to commit a breakpoint, which I did several times today :-)
That is something to think about in the future.

**Comment by jtesta** [comment]
I got those warnings from just running `tox`.  Here's the full output of `tox -r` up until those warnings:
```
$ tox -r
pypy3-test create: /home/jdog/Desktop/PS/ssh-audit/.tox/pypy3-test
ERROR: InterpreterNotFound: pypy3
pypy3-pylint create: /home/jdog/Desktop/PS/ssh-audit/.tox/pypy3-pylint
ERROR: InterpreterNotFound: pypy3
pypy3-flake8 create: /home/jdog/Desktop/PS/ssh-audit/.tox/pypy3-flake8
ERROR: InterpreterNotFound: pypy3
pypy3-vulture create: /home/jdog/Desktop/PS/ssh-audit/.tox/pypy3-vulture
ERROR: InterpreterNotFound: pypy3
py35-test recreate: /home/jdog/Desktop/PS/ssh-audit/.tox/py35-test
py35-test installdeps: pytest<6.0, coverage, colorama
py35-test installed: attrs==19.3.0,colorama==0.4.3,coverage==5.1,importlib-metadata==1.7.0,more-itertools==8.4.0,packaging==20.4,pathlib2==2.3.5,pkg-resources==0.0.0,pluggy==0.13.1,py==1.9.0,pyparsing==2.4.7,pytest==5.4.3,six==1.15.0,wcwidth==0.2.5,zipp==1.2.0
py35-test runtests: PYTHONHASHSEED='984453632'
py35-test runtests: commands[0] | coverage run --source ssh-audit -m -- pytest -v --junitxml=/home/jdog/Desktop/PS/ssh-audit/reports/junit.py35-test.xml test
====================================================== test session starts =======================================================
platform linux -- Python 3.5.2, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /home/jdog/Desktop/PS/ssh-audit/.tox/py35-test/bin/python3.5
cachedir: .pytest_cache
rootdir: /home/jdog/Desktop/PS/ssh-audit
collected 101 items                                                                                                              

test/test_auditconf.py::TestAuditConf::test_audit_conf_defaults PASSED                                                     [  0%]
test/test_auditconf.py::TestAuditConf::test_audit_conf_booleans PASSED                                                     [  1%]
test/test_auditconf.py::TestAuditConf::test_audit_conf_port PASSED                                                         [  2%]
test/test_auditconf.py::TestAuditConf::test_audit_conf_ipvo PASSED                                                         [  3%]
test/test_auditconf.py::TestAuditConf::test_audit_conf_level PASSED                                                        [  4%]
test/test_auditconf.py::TestAuditConf::test_audit_conf_cmdline PASSED                                                      [  5%]
test/test_banner.py::TestBanner::test_simple_banners PASSED                                                                [  6%]
test/test_banner.py::TestBanner::test_invalid_banners PASSED                                                               [  7%]
test/test_banner.py::TestBanner::test_banners_with_spaces PASSED                                                           [  8%]
test/test_banner.py::TestBanner::test_banners_without_software PASSED                                                      [  9%]
test/test_banner.py::TestBanner::test_banners_with_comments PASSED                                                         [ 10%]
test/test_banner.py::TestBanner::test_banners_with_multiple_protocols PASSED                                               [ 11%]
test/test_buffer.py::TestBuffer::test_unread PASSED                                                                        [ 12%]
test/test_buffer.py::TestBuffer::test_byte PASSED                                                                          [ 13%]
test/test_buffer.py::TestBuffer::test_bool PASSED                                                                          [ 14%]
test/test_buffer.py::TestBuffer::test_int PASSED                                                                           [ 15%]
test/test_buffer.py::TestBuffer::test_string PASSED                                                                        [ 16%]
test/test_buffer.py::TestBuffer::test_list PASSED                                                                          [ 17%]
test/test_buffer.py::TestBuffer::test_list_nonutf8 PASSED                                                                  [ 18%]
test/test_buffer.py::TestBuffer::test_line PASSED                                                                          [ 19%]
test/test_buffer.py::TestBuffer::test_line_nonutf8 PASSED                                                                  [ 20%]
test/test_buffer.py::TestBuffer::test_bitlen PASSED                                                                        [ 21%]
test/test_buffer.py::TestBuffer::test_mpint1 PASSED                                                                        [ 22%]
test/test_buffer.py::TestBuffer::test_mpint2 PASSED                                                                        [ 23%]
test/test_errors.py::TestErrors::test_connection_unresolved PASSED                                                         [ 24%]
test/test_errors.py::TestErrors::test_connection_refused PASSED                                                            [ 25%]
test/test_errors.py::TestErrors::test_connection_timeout PASSED                                                            [ 26%]
test/test_errors.py::TestErrors::test_recv_empty PASSED                                                                    [ 27%]
test/test_errors.py::TestErrors::test_recv_timeout PASSED                                                                  [ 28%]
test/test_errors.py::TestErrors::test_recv_retry_till_timeout PASSED                                                       [ 29%]
test/test_errors.py::TestErrors::test_recv_retry_till_reset PASSED                                                         [ 30%]
test/test_errors.py::TestErrors::test_connection_closed_before_banner PASSED                                               [ 31%]
test/test_errors.py::TestErrors::test_connection_closed_after_header PASSED                                                [ 32%]
test/test_errors.py::TestErrors::test_connection_closed_after_banner PASSED                                                [ 33%]
test/test_errors.py::TestErrors::test_empty_data_after_banner PASSED                                                       [ 34%]
test/test_errors.py::TestErrors::test_wrong_data_after_banner PASSED                                                       [ 35%]
test/test_errors.py::TestErrors::test_non_ascii_banner PASSED                                                              [ 36%]
test/test_errors.py::TestErrors::test_nonutf8_data_after_banner PASSED                                                     [ 37%]
test/test_errors.py::TestErrors::test_protocol_mismatch_by_conf PASSED                                                     [ 38%]
test/test_output.py::TestOutput::test_output_buffer_no_lines PASSED                                                        [ 39%]
test/test_output.py::TestOutput::test_output_buffer_no_flush PASSED                                                        [ 40%]
test/test_output.py::TestOutput::test_output_buffer_flush PASSED                                                           [ 41%]
test/test_output.py::TestOutput::test_output_defaults PASSED                                                               [ 42%]
test/test_output.py::TestOutput::test_output_colors PASSED                                                                 [ 43%]
test/test_output.py::TestOutput::test_output_sep PASSED                                                                    [ 44%]
test/test_output.py::TestOutput::test_output_levels PASSED                                                                 [ 45%]
test/test_output.py::TestOutput::test_output_level_property PASSED                                                         [ 46%]
test/test_output.py::TestOutput::test_output_level PASSED                                                                  [ 47%]
test/test_output.py::TestOutput::test_output_batch PASSED                                                                  [ 48%]
test/test_resolve.py::TestResolve::test_resolve_error PASSED                                                               [ 49%]
test/test_resolve.py::TestResolve::test_resolve_hostname_without_records PASSED                                            [ 50%]
test/test_resolve.py::TestResolve::test_resolve_ipv4 PASSED                                                                [ 51%]
test/test_resolve.py::TestResolve::test_resolve_ipv6 PASSED                                                                [ 52%]
test/test_resolve.py::TestResolve::test_resolve_ipv46_both PASSED                                                          [ 53%]
test/test_resolve.py::TestResolve::test_resolve_ipv46_order PASSED                                                         [ 54%]
test/test_socket.py::TestSocket::test_invalid_host PASSED                                                                  [ 55%]
test/test_socket.py::TestSocket::test_invalid_port PASSED                                                                  [ 56%]
test/test_socket.py::TestSocket::test_not_connected_socket PASSED                                                          [ 57%]
test/test_software.py::TestSoftware::test_unknown_software PASSED                                                          [ 58%]
test/test_software.py::TestSoftware::test_openssh_software PASSED                                                          [ 59%]
test/test_software.py::TestSoftware::test_dropbear_software PASSED                                                         [ 60%]
test/test_software.py::TestSoftware::test_libssh_software PASSED                                                           [ 61%]
test/test_software.py::TestSoftware::test_romsshell_software PASSED                                                        [ 62%]
test/test_software.py::TestSoftware::test_hp_ilo_software PASSED                                                           [ 63%]
test/test_software.py::TestSoftware::test_cisco_software PASSED                                                            [ 64%]
test/test_software.py::TestSoftware::test_software_os PASSED                                                               [ 65%]
test/test_ssh1.py::TestSSH1::test_crc32 PASSED                                                                             [ 66%]
test/test_ssh1.py::TestSSH1::test_fingerprint PASSED                                                                       [ 67%]
test/test_ssh1.py::TestSSH1::test_pkm_init PASSED                                                                          [ 68%]
test/test_ssh1.py::TestSSH1::test_pkm_read PASSED                                                                          [ 69%]
test/test_ssh1.py::TestSSH1::test_pkm_payload PASSED                                                                       [ 70%]
test/test_ssh1.py::TestSSH1::test_ssh1_server_simple PASSED                                                                [ 71%]
test/test_ssh1.py::TestSSH1::test_ssh1_server_invalid_first_packet PASSED                                                  [ 72%]
test/test_ssh1.py::TestSSH1::test_ssh1_server_invalid_checksum PASSED                                                      [ 73%]
test/test_ssh2.py::TestSSH2::test_kex_read PASSED                                                                          [ 74%]
test/test_ssh2.py::TestSSH2::test_key_payload PASSED                                                                       [ 75%]
test/test_ssh2.py::TestSSH2::test_ssh2_server_simple PASSED                                                                [ 76%]
test/test_ssh2.py::TestSSH2::test_ssh2_server_invalid_first_packet PASSED                                                  [ 77%]
test/test_ssh_algorithm.py::TestSSHAlgorithm::test_get_ssh_version PASSED                                                  [ 78%]
test/test_ssh_algorithm.py::TestSSHAlgorithm::test_get_since_text PASSED                                                   [ 79%]
test/test_ssh_algorithm.py::TestSSHAlgorithm::test_timeframe_creation PASSED                                               [ 80%]
test/test_ssh_algorithm.py::TestSSHAlgorithm::test_timeframe_object PASSED                                                 [ 81%]
test/test_utils.py::TestUtils::test_to_bytes PASSED                                                                        [ 82%]
test/test_utils.py::TestUtils::test_to_text PASSED                                                                         [ 83%]
test/test_utils.py::TestUtils::test_is_ascii PASSED                                                                        [ 84%]
test/test_utils.py::TestUtils::test_to_ascii PASSED                                                                        [ 85%]
test/test_utils.py::TestUtils::test_is_print_ascii PASSED                                                                  [ 86%]
test/test_utils.py::TestUtils::test_to_print_ascii PASSED                                                                  [ 87%]
test/test_utils.py::TestUtils::test_ctoi PASSED                                                                            [ 88%]
test/test_utils.py::TestUtils::test_parse_int PASSED                                                                       [ 89%]
test/test_utils.py::TestUtils::test_unique_seq PASSED                                                                      [ 90%]
test/test_version_compare.py::TestVersionCompare::test_dropbear_compare_version_pre_years PASSED                           [ 91%]
test/test_version_compare.py::TestVersionCompare::test_dropbear_compare_version_with_years PASSED                          [ 92%]
test/test_version_compare.py::TestVersionCompare::test_dropbear_compare_version_mixed PASSED                               [ 93%]
test/test_version_compare.py::TestVersionCompare::test_dropbear_compare_version_patchlevel PASSED                          [ 94%]
test/test_version_compare.py::TestVersionCompare::test_dropbear_compare_version_sequential PASSED                          [ 95%]
test/test_version_compare.py::TestVersionCompare::test_openssh_compare_version_simple PASSED                               [ 96%]
test/test_version_compare.py::TestVersionCompare::test_openssh_compare_version_patchlevel PASSED                           [ 97%]
test/test_version_compare.py::TestVersionCompare::test_openbsd_compare_version_sequential PASSED                           [ 98%]
test/test_version_compare.py::TestVersionCompare::test_libssh_compare_version_simple PASSED                                [ 99%]
test/test_version_compare.py::TestVersionCompare::test_libssh_compare_version_sequential PASSED                            [100%]

======================================================== warnings summary ========================================================
.tox/py35-test/lib/python3.5/site-packages/_pytest/junitxml.py:417
  /home/jdog/Desktop/PS/ssh-audit/.tox/py35-test/lib/python3.5/site-packages/_pytest/junitxml.py:417: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0.
  Add 'junit_family=xunit1' to your pytest.ini file to keep the current format in future versions of pytest and silence this warning.
    _issue_warning_captured(deprecated.JUNIT_XML_DEFAULT_FAMILY, config.hook, 2)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
------------------------ generated xml file: /home/jdog/Desktop/PS/ssh-audit/reports/junit.py35-test.xml -------------------------
================================================= 101 passed, 1 warning in 0.39s =================================================
py35-test runtests: commands[1] | coverage report --show-missing
Name           Stmts   Miss  Cover   Missing
--------------------------------------------
ssh-audit.py    1970    340    83%   135, 170, 174, 181-183, 202-204, 575, 581, 587, 675-677, 680, 684-763, 772-794, 815-882, 1199, 1390-1393, 1409, 1412, 1652, 1683, 1714, 1719, 1725-1732, 1734, 1946-1995, 2074-2076, 2110-2111, 2175, 2378, 2383, 2389-2390, 2396-2397, 2402, 2407-2410, 2415, 2423-2425, 2430, 2434-2436, 2441, 2445-2447, 2452, 2455, 2466-2498, 2503, 2508, 2524, 2531-2537, 2541, 2556, 2559, 2577-2579, 2586, 2596, 2600, 2606, 2631, 2641, 2644-2645, 2671-2682, 2703-2727, 2737, 2751-2754, 2762, 2774, 2792, 2813, 2946-2947, 2951-3025, 3035, 3059-3060, 3079, 3088, 3098-3099
py35-test runtests: commands[2] | coverage html -d /home/jdog/Desktop/PS/ssh-audit/reports/html/coverage.py35-test
py35-mypy recreate: /home/jdog/Desktop/PS/ssh-audit/.tox/py35-mypy
py35-mypy installdeps: colorama, colorama, lxml, mypy
py35-mypy installed: colorama==0.4.3,lxml==4.5.1,mypy==0.782,mypy-extensions==0.4.3,pkg-resources==0.0.0,typed-ast==1.4.1,typing-extensions==3.7.4.2
py35-mypy runtests: PYTHONHASHSEED='984453632'
py35-mypy runtests: commands[0] | -mypy --show-error-context --config-file /home/jdog/Desktop/PS/ssh-audit/tox.ini --html-report /home/jdog/Desktop/PS/ssh-audit/reports/html/mypy.py3.py35-mypy /home/jdog/Desktop/PS/ssh-audit/ssh-audit.py
Generated HTML report (via XSLT): /home/jdog/Desktop/PS/ssh-audit/reports/html/mypy.py3.py35-mypy/index.html
Success: no issues found in 1 source file
py35-pylint recreate: /home/jdog/Desktop/PS/ssh-audit/.tox/py35-pylint
py35-pylint installdeps: mccabe, pylint
py35-pylint installed: astroid==2.4.2,isort==4.3.21,lazy-object-proxy==1.4.3,mccabe==0.6.1,pkg-resources==0.0.0,pylint==2.5.3,six==1.15.0,toml==0.10.1,typed-ast==1.4.1,wrapt==1.12.1
py35-pylint runtests: PYTHONHASHSEED='984453632'
py35-pylint runtests: commands[0] | -pylint --rcfile tox.ini --load-plugins=pylint.extensions.bad_builtin --load-plugins=pylint.extensions.check_elif --load-plugins=pylint.extensions.mccabe /home/jdog/Desktop/PS/ssh-audit/ssh-audit.py
************* Module ssh-audit
ssh-audit.py:97:73: E1136: Value 'Sequence' is unsubscriptable (unsubscriptable-object)
ssh-audit.py:1613:27: E1136: Value 'Sequence' is unsubscriptable (unsubscriptable-object)
ssh-audit.py:1896:74: E1136: Value 'Sequence' is unsubscriptable (unsubscriptable-object)
ssh-audit.py:1920:33: E1136: Value 'Sequence' is unsubscriptable (unsubscriptable-object)
ssh-audit.py:2916:29: E1136: Value 'Sequence' is unsubscriptable (unsubscriptable-object)
ssh-audit.py:2916:47: E1136: Value 'Sequence' is unsubscriptable (unsubscriptable-object)

------------------------------------------------------------------
Your code has been rated at 9.85/10 (previous run: 9.85/10, +0.00)
```

I'll merge this PR anyway.

**Comment by jugmac00** [comment]
Thanks! And sorry for the inconvenience.

I searched the mypy docs and found this:

> # Use Iterable for generic iterables (anything usable in "for"),
# and Sequence where a sequence (supporting "len" and "__getitem__") is
# required

https://mypy.readthedocs.io/en/stable/cheat_sheet.html?highlight=sequence#standard-duck-types

And `__getitem__` exactly enables the access via index (the opposite of unsubscriptable).

So, I guess this is another false-positive of pylint.

**Pull request merged**
