### PR TITLE
Argparse v2

### PR DESCRIPTION
**Pull request by oam7575**
Version 2 of the argparse change.

Issue : #297
Implement argparse
Remove getopts

### CODE REVIEW

**Comment by ikwyl6** [comment]
Why are you submitting all your changes to your previous commit(s)? Why not just do all that locally on your machine and then just submit your RC2 commit (or the very last commit that is the diff)? 
Also you can group your '-h' and '--help' (and all other short and long args) on the same argparse line instead of breaking them up into separate lines ('-1' with '-ssh1' and so on). 
Just my 2cents.

**Comment by oam7575** [comment]
Hey @ikwyl6 

I'm about the furthest thing from an expert there is.
The points you raise can be summarized as "lack of experience".

As for the submitting a single commit; I am aware of "squashing commits" ; but using Git Extensions on Windows I am a little unsure on how to achieve that

I'll have another look and see how I go.

**Comment by oam7575** [comment]
Hi @ikwyl6 

As can be seen by my attempts, having a little trouble with git extensions and squashing the commits.
If you could point me to some simple resources for learning git / git-extensions ( any other suggestion ) it would be appreciated.

I did try following this page : https://stackoverflow.com/questions/46733179/git-extensions-squash-commits ; but no joy.

With that said - I will happily close this PR and open a fresh one that should hopefully, but a little cleaner ( again )

**Comment by oam7575** [comment]
See PR : Argparse v3 - RC1 #304

**Pull request closed without merging**
