### PR TITLE
Updated VulnerabilityDB & more fingerprint algorithms

### PR DESCRIPTION
**Pull request by manfred-kaiser**
* remove unused imports and noqa comments (except pylint's unused import comment)
* removed arguments from super() to match python3 style guide
* removed unnecesary "else" after "return"
* removed unused or wrong pylint arguments from tox.ini

### CODE REVIEW

**Comment by hmaier1996** [comment]
I have updated the vulnerability database and added missing CVEs to OpenSSH, PuTTY and Dropbear.

There was also an open issue ticket #156, which complains about missing fingerprint algorithms. This feature was also added to the pull request.

**Comment by hmaier1996** [comment]
@manfred-kaiser Oh, you have already added the fingerprints and updated the vulnerability database :-( This should fix as i mentioned in #155

**Comment by hmaier1996** [comment]
> @manfred-kaiser Oh, you have already added the fingerprints and updated the vulnerability database :-( This should fix as i mentioned in #155

This was a really quick fix :+1:

**Comment by manfred-kaiser** [comment]
this pull request was closed because #157 only updates the vulnerability database and the other changes are not necessary (see #102)

**Pull request closed without merging**
