### PR TITLE
Fix typing errors

### PR DESCRIPTION
**Pull request by jugmac00**
**Strategy**
This is similar to the approach with Flake8.
- remove all config options
- fix any leftover typing problem
- convert type comments to type annotations
- (maybe) add back some options, one bye one

### CODE REVIEW

**Comment by jtesta** [comment]
I see that you're updating the type comments.  Is that the best way to 
go?  I thought Python built in optional types into the language syntax 
itself.  Would that be better?

**Comment by jugmac00** [comment]
First, there were type comments - compatible both with Python 2 and Python 3 (that is what we have now - partially present, and partially broken).

From afaik Python 3.5 the standard library contains the typing module and type annotations are possible (maybe from 3.4?), that is no longer using the comments, but write type info directly e.g. to the parameters (e.g. `def greeting(name: str) -> str:`)

So, the preferred way is certainly using type annotations.

There is a converter out there ( https://github.com/ilevkivskyi/com2ann ), which can automatically convert the type comments into type annotations, but the converter breaks, because for several methods/functions, the number of parameters were changed, but not the type comments.

So, as written above in the first PR comment, after I deactivated the strict mypy options, I try to fix the 47 leftover errors, then auto-convert the type comments to type annotations.

This may take a while, as 
a) fixing one error, possibly (and actually) reveals tons of consequential errors
b) I just started learning Python typing
c) I really have to read a lot of code, so I understand what kind of type some parameters really are- it is not always very clear from the parameter name

**Comment by jtesta** [comment]
Ok.  I just wanted to make sure that you considered type annotations.  I 
don't have a preference either way.  Just don't feel like you're forced 
to use type comments since they're already in the code.  If you decide 
annotations are better, I have no problem throwing the comments out.

This is your project, so you can do what you want!

**Comment by jugmac00** [comment]
I fixed all 47 type errors which were shown without the additional stricter options in tox.ini.

```
❯ tox -e mypy
mypy installed: colorama==0.4.3,lxml==4.5.1,mypy==0.770,mypy-extensions==0.4.3,typed-ast==1.4.1,typing-extensions==3.7.4.2
mypy run-test-pre: PYTHONHASHSEED='3898913091'
mypy run-test: commands[0] | -mypy --show-error-context --config-file /home/jugmac00/Projects/ssh-audit/tox.ini --html-report /home/jugmac00/Projects/ssh-audit/reports/html/mypy.py3.mypy /home/jugmac00/Projects/ssh-audit/ssh-audit.py
ssh-audit.py: note: In member "__setattr__" of class "AuditConf":
ssh-audit.py:136: error: Incompatible types in assignment (expression has type "float", variable has type "Union[str, int, bool, Sequence[int]]")
ssh-audit.py: note: In member "from_cmdline" of class "AuditConf":
ssh-audit.py:196: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:206: error: Incompatible types in assignment (expression has type "None", variable has type "str")
ssh-audit.py: note: At top level:
ssh-audit.py:288: error: Type signature has too few arguments
ssh-audit.py: note: In member "__init__" of class "Kex":
ssh-audit.py:561: error: Need type annotation for '__rsa_key_sizes' (hint: "__rsa_key_sizes: Dict[<type>, <type>] = ...")
ssh-audit.py:562: error: Need type annotation for '__dh_modulus_sizes' (hint: "__dh_modulus_sizes: Dict[<type>, <type>] = ...")
ssh-audit.py:563: error: Need type annotation for '__host_keys' (hint: "__host_keys: Dict[<type>, <type>] = ...")
ssh-audit.py: note: In member "compare_version" of class "Software":
ssh-audit.py:1344: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:1362: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:1364: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py: note: In member "display" of class "Software":
ssh-audit.py:1390: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:1391: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py: note: In member "_extract_os_version" of class "Software":
ssh-audit.py:1434: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:1440: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:1446: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py: note: In member "parse" of class "Software":
ssh-audit.py:1462: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:1465: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:1468: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:1472: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:1475: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:1478: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:1481: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:1484: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:1487: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:1489: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:1493: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:1497: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:1500: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:1503: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py: note: In member "parse" of class "Banner":
ssh-audit.py:1565: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:1567: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:1568: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py:1570: error: Item "None" of "Optional[Match[str]]" has no attribute "group"
ssh-audit.py: note: In member "get_recommendations" of class "Algorithms":
ssh-audit.py:1807: error: Item "None" of "Optional[str]" has no attribute "split"
ssh-audit.py: note: At top level:
ssh-audit.py:2024: error: Type signature has too few arguments
ssh-audit.py:2321: error: Type signature has too few arguments
ssh-audit.py:2348: error: Type signature has too few arguments
ssh-audit.py:2514: error: Type signature has too few arguments
ssh-audit.py:2656: error: Type signature has too few arguments
ssh-audit.py:2667: error: Type signature has too few arguments
ssh-audit.py:2729: error: Type signature has too few arguments
ssh-audit.py:2760: error: Type signature has too few arguments
ssh-audit.py:2791: error: Type signature has too few arguments
ssh-audit.py:2804: error: Type signature has too many arguments
ssh-audit.py: note: In function "output_recommendations":
ssh-audit.py:2873: error: No return value expected
ssh-audit.py:2912: error: No return value expected
ssh-audit.py: note: At top level:
ssh-audit.py:2932: error: Type signature has too few arguments
Generated HTML report (via XSLT): /home/jugmac00/Projects/ssh-audit/reports/html/mypy.py3.mypy/index.html
Found 47 errors in 1 file (checked 1 source file)
```

As I do not have much time in the next couple of days, I think it would be a good idea to merge this PR.

There are some more todos for future PRs, like
- make up ones mind about the additional mypy options (which one of them makes sense? if so, activate them one by one and fix the errors)
- convert to type annotations ( I gave it a quick shot, but this resulted in completely broken syntax - not sure whether this is the converter's problem)

**Comment by jtesta** [comment]
Nice work!  Thanks!

**Pull request merged**
